repos:
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort .
        pass_filenames: false
        language: system
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.770'
    hooks:
      - id: mypy
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: poetry run python manage.py test
        language: system
        types: [python]
        pass_filenames: false
