version: "3.3"

services:
    app:
        depends_on:
            - db
        env_file:
            - .env
        build:
            context: .
            args:
                INSTALL_DEV: ${INSTALL_DEV}
        volumes:
            - ./static:/app/static
            - ./media:/app/media
        ports:
            - 8899:8000

    nginx:
        build: ./nginx
        volumes:
            - ./static:/www/static
            - ./media:/www/media
        ports:
            - ${PORT}:80
        depends_on:
            - app
        # restart: always

    db:
        image: postgres:13.4-buster
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASS}
            - TZ=${TIME_ZONE}
        ports:
            - ${EXTERNAL_DATABASE_PORT}:5432
        volumes:
            - db:/var/lib/postgresql/data
        # restart: always

volumes:
    db:
